version: "3.8"

services:
  appvm:
    build:
      context: ./appvm
      dockerfile: Dockerfile
    restart: on-failure
    container_name: qwantify-john-wick
    command: supervisord #run supervisord on container run
    ports:
      - 3000:3000
    environment:
      - screenwidth=1280
      - screenheight=1024
      - appname=John Wick Hex
      - apppath=/appvm/apps/John-Wick-Hex
      - appfile=John Wick Hex.exe
      #- wineoptions=
    volumes:
      - /home/ec2-user/games:/appvm/apps #map game files onto the docker container for wine