version: "3.8"

services:
  appvm:
    build:
      context: ./appvm
      dockerfile: Dockerfile
      args:
        APP_NAME: tarzan_pc #${APP_NAME}
    restart: on-failure
    container_name: qwantify-tarzan_pc
    command: supervisord #run supervisord on container run
    ports:
      - 3000:3000
    environment:
      - screenwidth=1280
      - screenheight=1024
      - appname=Tarzan
      - apppath=/appvm/apps/tarzan_pc/game
      - appfile=tarzan.exe
      #- wineoptions=
    volumes:
      - ./appvm/apps:/appvm/apps #map game files onto the docker container for wine